version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "samyak3009/s3bucket:1.4"
    ports:
      - "3001:3001"
    env_file:
     - ./a.env
  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    image: "samyak3009/frontend:1.0"
    ports:
      - "3000:3000"
    links:
      - "backend:be"